### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by Foorack** [IntellectualSites/PlotSquaredSuggestions#1]
Migration of https://github.com/IntellectualSites/PlotSquared/issues/19

**Comment by Foorack** [comment]
Reason for closure?

**Comment by Draycia** [comment]
I imagine it was closed because it was declined.

**Comment by Foorack** [comment]
@Draycia Very unhelpful comment, this has been as approved for a very long time, and it was switched to declined just before closing it.

**Comment by MattBDev** [comment]
City must have changed his mind on this issue. If it helps at all I could make sure that all the database code is abstracted or put in an interface so a Mongo DB addon could be made for it.

**Comment by Sauilitired** [comment]
It's fine if someone were to create a pull request for this. It being approved make it seem as if **we** are going to implement it, which we are **not** going to do.

So, the suggestion that we are going to add MongoDB support to PlotSquared won't be approved, because there's no demand for it. However, I won't stop anyone else from doing it.

**Comment by Foorack** [comment]
Thank you for the explanation :)
