### ISSUE TITLE
Swap plot order numbers

### ISSUE THREAD

**Issue by Mwthorn** [IntellectualSites/PlotSquaredSuggestions#72]
**PlotSquared Feature Suggestion:**
Players are able to use "/plot home (number)" when they have multiple plots, which is fine.
However, some of them would like to swap the order in which the number represent a plot.
As far as I'm aware, they need this to allow other players to view their best plots in a specific order.

**How should it be implemented?**
Since "/plot swap" already exists for literrally swaping plots, I suggest "/plot swapid (number) (number)" where the numbers are the plot order in "/plot home (number)"

**Additional context**
Simply copying/pasting the buildings on the different plots for a manuel swap won't work if the plots have different sizes and forms.

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users
This was suggested by a few users, not me.

**Comment by AeSix** [comment]
I think allowing players to set their homes by name (with name being limited to numbers, possibly) would be a better solution, and having it so that players with a single home, or a home with no name can be accessed as currently.  

This would allow for the players to set their homes in the order they would like (if by number only) or at least give a friendly name for their homes (if by word name)  

The plotid could be given in the chat as well:

Notch (example player) would have 2 plots: 20;20 and 21;20
for 20;20, he would do ```/plot sethome 0```  to set his first/basic home
for 20;21, he would do ```/plot sethome coolplotbro``` for his named home

Other players would do:
```/p home Notch``` or ```/p home Notch 0``` and be taken to 20;20
Chat output would be something like
```Teleporting you to Notch's home at 20;20```

doing
```/plot home Notch coolplotbro```
would take players to 20;21, with output
```Teleporting you to Notch's coolplotbro at 20;21```

Adding the plotid would be useful for administrative tasks, as well as for players to know /where/ in the world they're going.  

The current system could remain in place, allowing for the current usual method of going to player's plots as well.

**Comment by N0tMyFaultOG** [comment]
Described behavior already exists by giving the plot an alias.
Plots are ordered by their timestamp of creation, so messing with the pagination will also mess with some other tasks, e.g. expiry.
